#!/bin/sh

sudo /opt/zeek/bin/zeekctl stop
sudo cp /opt/zeek/etc/node.cfg /opt/zeek/etc/node.cfg.old
sudo rm /opt/zeek/etc/node.cfg
sudo cp ./node.cfg /opt/zeek/etc/ # Interface AWS
sudo chmod 664 /opt/zeek/etc/node.cfg
sudo chown root:zeek /opt/zeek/etc/node.cfg # Dono root, grupo zeek

active_interface=$(ip route | grep default | awk '{print $5}') # Encontra a interface de rede ativa
config_file="/opt/zeek/etc/node.cfg" # Define o caminho do arquivo de configuração
sudo sed -i "s/interface=.*/interface=$active_interface/g" $config_file # Substitui todas as ocorrências de "interface=" pelo valor da interface ativa
echo "\ninterface=$active_interface" | sudo tee -a /opt/zeek/etc/node.cfg
