#!/bin/sh

sudo apt update -y
sudo apt install -y curl

# sudo apt-get -y install cmake make gcc g++ flex libfl-dev bison libpcap-dev libssl-dev python3 python3-dev swig zlib1g-dev

# Escolher o repositorio adequado a versao do Debian em https://software.opensuse.org/download.html?project=security%3Azeek&package=zeek-lts
sudo cat /etc/debian_version
# ATENCAO: ESSE REPOSITORIO SOH FUNCIONA NO DEBIAN 12
sudo echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
sudo curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
sudo apt -y update
sudo apt -y install zeek-lts -f
sudo setcap cap_net_raw=eip /opt/zeek/bin/zeek
sudo setcap cap_net_raw=eip /opt/zeek/bin/capstats
sudo bash -c 'echo "ZeekPort = 27760" >> /opt/zeek/etc/zeekctl.cfg'
export PATH=/opt/zeek/bin:$PATH

sudo /opt/zeek/bin/zeekctl stop
sudo cp /opt/zeek/etc/node.cfg /opt/zeek/etc/node.cfg.old
sudo rm /opt/zeek/etc/node.cfg
sudo cp ./node.cfg /opt/zeek/etc/ # Interface AWS
sudo chmod 664 /opt/zeek/etc/node.cfg
sudo chown root:zeek /opt/zeek/etc/node.cfg # Dono root, grupo zeek

active_interface=$(ip route | grep default | awk '{print $5}') # Encontra a interface de rede ativa
config_file="/opt/zeek/etc/node.cfg" # Define o caminho do arquivo de configuração
sudo sed -i "s/interface=.*/interface=$active_interface/g" $config_file # Substitui todas as ocorrências de "interface=" pelo valor da interface ativa
echo "\ninterface=$active_interface" | sudo tee -a /opt/zeek/etc/node.cfg

# Transformar os logs do Zeek para JSON
sudo cp ./hash_sha256.zeek /opt/zeek/share/zeek/site/hash_sha256.zeek
sudo cp /opt/zeek/share/zeek/site/local.zeek /opt/zeek/share/zeek/site/local.zeek.old
sudo rm /opt/zeek/share/zeek/site/local.zeek
sudo cp ./local.zeek /opt/zeek/share/zeek/site
sudo chmod 664 /opt/zeek/share/zeek/site/local.zeek
sudo chown root:zeek /opt/zeek/share/zeek/site/local.zeek # Dono root, grupo zeek

sudo /opt/zeek/bin/zeekctl stop
sudo pip config set global.break-system-packages True
sudo pip3 install GitPython semantic-version --user
sudo /opt/zeek/bin/zkg autoconfig
sudo /opt/zeek/bin/zkg refresh
sudo /opt/zeek/bin/zkg upgrade
sudo /opt/zeek/bin/zkg install --force zeek/hosom/file-extraction
sudo /opt/zeek/bin/zkg load zeek/hosom/file-extraction
sudo /opt/zeek/bin/zeekctl deploy
